//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhsneuro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionSymptom
    {
        public int SymptomID { get; set; }
        public int ConditionID { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Symptom Symptom { get; set; }
    }
}
